INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 801-066-297
INFO:werkzeug: * Detected change in 'C:\\Users\\Admin\\PycharmProjects\\Facedetection_matched_ML\\app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 801-066-297
INFO:werkzeug: * Detected change in 'C:\\Users\\Admin\\PycharmProjects\\Facedetection_matched_ML\\app.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 801-066-297
INFO:root:User 9lQbHFCFN7gwUiAWAAAB connected
ERROR:root:frame does not detect a proper face
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:frame does not detect a proper face
ERROR:root:frame does not detect a proper face
ERROR:root:frame does not detect a proper face
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
ERROR:root:Error: name 'image_database' is not defined
INFO:werkzeug: * Detected change in 'C:\\Users\\Admin\\PycharmProjects\\Facedetection_matched_ML\\app.py', reloading
INFO:werkzeug: * Restarting with stat
